import '@mantine/core/styles.css';
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {createTheme, MantineProvider} from "@mantine/core";

const inter = Inter({subsets: ["latin"]});

const theme = createTheme({
	/** Your theme override here */
});


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
																		 children,
																	 }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body className={inter.className}>
		<MantineProvider theme={theme} defaultColorScheme='light'>
			{children}
		</MantineProvider>
		</body>
		</html>
	);
}
